on:
  push:
    branches:
    - 'main' # Push events to main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
name: Calculate Version

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      with:
        extra_plugins: |
          @semantic-release/git
          @semantic-release/exec
          @semantic-release/changelog
