on:
  push:
    branches:
    - 'main' # Push events to main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
name: Calculate Version

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  verion:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
    - name: Add plugin for conventional commits
      run: npm install conventional-changelog-conventionalcommits
      working-directory: ./.github/workflows
    - name: Release to GitHub
      working-directory: ./.github/workflows
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release
