on:
  push:
    branches:
    - 'main' # Push events to main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
name: Create Release

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      id: semantic
      with:
        extra_plugins: |
          @semantic-release/git
          @semantic-release/changelog
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Replace Version
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "SEMANTIC_VERSION_NUMBER"
        replace: ${{ steps.semantic.outputs.new_release_version }}

    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'GhostWriter.ext'
        exclusions: '*.git* *.github* *.resources* /*node_modules/* .editorconfig *.ext .releaserc'

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "GhostWriter.ext"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
