on:
  push:
    branches:
    - 'main' # Push events to main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
name: Create Release

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Determine Version
      id: semantic
      uses: codacy/git-version@2.2.0
      with:
        prefix: 'v'
        release-branch: 'main'

    - name: Replace Version
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "SEMANTIC_VERSION_NUMBER"
        replace: ${{ steps.semantic.output.version }}

    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'GhostWriter.ext'
        exclusions: '*.git* *.github* *.resources* /*node_modules/* .editorconfig *.ext .releaserc'

    - name: Push Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "GhostWriter.ext"
        tag: ${{ steps.semantic.output.version }}
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
