on:
  push:
    branches:
    - 'main' # Push events to main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
name: Create Release

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id: semantic
      uses: gittools/actions/gitversion/execute@v0.9.7

    - name: Replace Version
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "SEMANTIC_VERSION_NUMBER"
        replace: "$GITVERSION_SEMVER"

    - name: Create Release
      uses: actions/create-release@v1
      with:
        draft: false
        prerelease: false
        release_name: "$GITVERSION_SEMVER"
        tag_name: "$GITVERSION_SEMVER"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'GhostWriter.ext'
        exclusions: '*.git* *.github* *.resources* /*node_modules/* .editorconfig *.ext .releaserc'

    - name: Push Release
      uses: actions/upload-artifact@v2
      with:
        name: 'GhostWriter.ext'
        path: 'GhostWriter.ext'
